from collections.abc import Callable
from typing import Any, Union

def get_callable(lookup_view: Union[Callable[..., Any], str]) -> Callable[..., Any]: ...
def get_mod_func(callback: str) -> tuple[str, str]: ...
