from typing import Any, Optional, Union

from django.template.base import Origin
from django.template.engine import Engine

from .base import Loader as BaseLoader

class Loader(BaseLoader):
    dirs: Optional[list[str]] = ...
    def __init__(self, engine: Engine, dirs: Optional[list[str]] = ...) -> None: ...
    def get_dirs(self) -> Union[list[bytes], list[str]]: ...
    def get_contents(self, origin: Origin) -> Any: ...
