from collections.abc import Callable, Sequence
from typing import Any, Optional, Union

from django.template.base import Origin
from django.template.library import Library
from django.template.loaders.base import Loader
from django.utils.safestring import SafeText

from .base import Template

_Loader = Any

class Engine:
    template_context_processors: tuple[Callable[..., Any]]
    template_loaders: list[Loader]
    default_builtins: Any = ...
    dirs: list[str] = ...
    app_dirs: bool = ...
    autoescape: bool = ...
    context_processors: Union[list[str], tuple[str]] = ...
    debug: bool = ...
    loaders: Sequence[_Loader] = ...
    string_if_invalid: str = ...
    file_charset: str = ...
    libraries: dict[str, str] = ...
    template_libraries: dict[str, Library] = ...
    builtins: list[str] = ...
    template_builtins: list[Library] = ...
    def __init__(
        self,
        dirs: Optional[list[str]] = ...,
        app_dirs: bool = ...,
        context_processors: Optional[Union[list[str], tuple[str]]] = ...,
        debug: bool = ...,
        loaders: Optional[Sequence[_Loader]] = ...,
        string_if_invalid: str = ...,
        file_charset: str = ...,
        libraries: Optional[dict[str, str]] = ...,
        builtins: Optional[list[str]] = ...,
        autoescape: bool = ...,
    ) -> None: ...
    @staticmethod
    def get_default() -> Engine: ...
    def get_template_builtins(self, builtins: list[str]) -> list[Library]: ...
    def get_template_libraries(
        self, libraries: dict[str, str]
    ) -> dict[str, Library]: ...
    def get_template_loaders(
        self, template_loaders: Sequence[_Loader]
    ) -> list[Loader]: ...
    def find_template_loader(self, loader: _Loader) -> Loader: ...
    def find_template(
        self, name: str, dirs: None = ..., skip: Optional[list[Origin]] = ...
    ) -> tuple[Template, Origin]: ...
    def from_string(self, template_code: str) -> Template: ...
    def get_template(self, template_name: str) -> Template: ...
    def render_to_string(
        self, template_name: str, context: Optional[dict[str, Any]] = ...
    ) -> SafeText: ...
    def select_template(self, template_name_list: list[str]) -> Template: ...
